language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
script: sbt ++$TRAVIS_SCALA_VERSION compile test package
matrix:
  fast_finish: true
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f8c76df769344205cb16
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false
