language: scala
scala:
  - 2.11.4
  - 2.10.4
jdk:
  - oraclejdk8
  - oraclejdk7
script: sbt ++$TRAVIS_SCALA_VERSION compile test package
matrix:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk7
    - scala: 2.10.4
